# Generated by Django 2.0.6 on 2018-12-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_quiz_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_questions',
            name='answers',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz_questions',
            name='choice1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz_questions',
            name='choice2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz_questions',
            name='choice3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz_questions',
            name='choice4',
            field=models.CharField(max_length=100),
        ),
    ]
