# Generated by Django 2.0.6 on 2018-12-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0004_auto_20181217_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=30)),
                ('score', models.IntegerField()),
                ('answer', models.CharField(max_length=500)),
            ],
        ),
    ]
