# Generated by Django 2.0.6 on 2018-12-18 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0006_auto_20181217_2338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_score',
            new_name='Results',
        ),
    ]
