# Generated by Django 2.0.6 on 2018-12-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0008_auto_20181218_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_results',
            name='answer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user_results',
            name='user_answer',
            field=models.CharField(max_length=200),
        ),
    ]
